version: "3.8"
services:
  mysqldb:
    image: mysql:8.4.6
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 10
      timeout: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
    external: true
